### ISSUE TITLE
View Data

### ISSUE THREAD

**Issue by ksassnowski** [aoporanu/arcanist-test#1]
Hey, let’s move this over here instead of doing this on YouTube. Which step in particular is giving you trouble?

**Comment by aoporanu** [comment]
haven't checked past ClientsAndShops as it is hanging on this issue. i could get the valdidation errors when both the client_id and shop_id were simple inputs, but validation is stored in the steps array to my understanding

**Comment by aoporanu** [comment]
i was able to get as far as the createorderaction, and i guess i could have the view data dynamically added on both of the select fields to populate them, since this is just from a pet project, but i just want to know why it works in your tutorial and not in my case

**Comment by ksassnowski** [comment]
So it's this line where you don't get any data from the backend? https://github.com/aoporanu/arcanist-test/blob/main/wizards/order/client-and-shop.blade.php#L23

**Comment by ksassnowski** [comment]
It just occurred to me that you’re trying to access the view data using the `$data` variable. The variable is actually called `$wizard`, however. So instead of `$data['clients']` you would have to use `$wizard['clients']`. I think this is something that changed between the YouTube video and the release. The docs use the correct variable name, however: https://laravel-arcanist.com/getting-started#accessing-data-in-a-view

**Comment by aoporanu** [comment]
> It just occurred to me that you’re trying to access the view data using the `$data` variable. The variable is actually called `$wizard`, however. So instead of `$data['clients']` you would have to use `$wizard['clients']`. I think this is something that changed between the YouTube video and the release. The docs use the correct variable name, however: https://laravel-arcanist.com/getting-started#accessing-data-in-a-view

i'll try the fix later tonight and i'll come back with an answer.

**Comment by aoporanu** [comment]
Still nothing, 
https://imgur.com/KC99vZo

**Comment by ksassnowski** [comment]
Ah sorry, I mixed it up. The view data is contained in the `$step` variable. `$wizard` contains all the meta data of the wizard. Anything inside `$step`?

**Comment by aoporanu** [comment]
Now we're cooking with gas!
You Kai, are indeed a wizard. Thank you very much for taking your time to guide me through this.
